site:
  title: Implicated
  url: https://docs.demo.com
  start_page: asciidoc::index.adoc
content:
  sources:
    - url: https://github.com/implicated/docs.git
      start_paths:
        - asciidoc
      branches: HEAD
ui:
  bundle:
    url: https://github.com/implicated/implicated.github.io/blob/master/ui-bundle.zip
    snapshot: true
