site:
  title: Implicated
  url: https://docs.demo.com
  start_page: asciidoc::index.adoc
content:
  sources:
    - url: ../docs
      start_paths:
        - asciidoc
        - linux
      branches: 'master'
ui:
  bundle:
    url: ui-bundle.zip
#    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    #    url: https://github.com/aerogear/antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
output:
  clean: true
